name: combat_tracker
description: "A simple combat tracker for ttrpg games."
publish_to: 'none'
version: 0.5.0+7

environment:
  sdk: ^3.10.1

dependencies:
  collection: ^1.19.1
  crypto: ^3.0.7
  dynamic_color: ^1.8.1
  file_picker: ^10.3.8
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  
  flutter_svg: ^2.2.3
  font_awesome_flutter: ^10.12.0
  gap: ^3.0.1
  intl: ^0.20.2
  macos_secure_bookmarks: ^0.2.1
  package_info_plus: ^9.0.0
  path: ^1.9.1
  protobuf: ^6.0.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  window_manager: ^0.5.1
  xxh3: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.svg

  fonts:
    - family:  CustomIcons
      fonts:
       - asset: fonts/CustomIcons.ttf

flutter_launcher_icons:
  image_path: "assets/icon/icon.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  android: false
  ios: false
  
