name: combat_tracker
description: "A simple combat tracker for ttrpg games."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  dynamic_color: ^1.8.1
  fixnum: ^1.1.1
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.12.0
  gap: ^3.0.1
  protobuf: ^6.0.0
  uuid: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
